export const editGridComponents = [
  {
    label: 'Edit Grid',
    labelPosition: 'top',
    description: 'description',
    tooltip: '',
    customClass: '',
    tabindex: '',
    openWhenEmpty: false,
    disableAddingRemovingRows: false,
    conditionalAddButton: '',
    hidden: false,
    hideLabel: false,
    autofocus: false,
    disabled: false,
    tableView: false,
    modalEdit: false,
    templates: {
      // eslint-disable-next-line max-len
      header: '<div class="row">\n      {% util.eachComponent(components, function(component) { %}\n        {% if (displayValue(component)) { %}\n          <div class="col-sm-2">{{ t(component.label) }}</div>\n        {% } %}\n      {% }) %}\n    </div>',
      // eslint-disable-next-line max-len
      row: "<div class=\"row\">\n      {% util.eachComponent(components, function(component) { %}\n        {% if (displayValue(component)) { %}\n          <div class=\"col-sm-2\">\n            {{ isVisibleInRow(component) ? getView(component, row[component.key]) : ''}}\n          </div>\n        {% } %}\n      {% }) %}\n      {% if (!instance.options.readOnly && !instance.disabled) { %}\n        <div class=\"col-sm-2\">\n          <div class=\"btn-group pull-right\">\n            <button class=\"btn btn-default btn-light btn-sm editRow\"><i class=\"{{ iconClass('edit') }}\"></i></button>\n            {% if (!instance.hasRemoveButtons || instance.hasRemoveButtons()) { %}\n              <button class=\"btn btn-danger btn-sm removeRow\"><i class=\"{{ iconClass('trash') }}\"></i></button>\n            {% } %}\n          </div>\n        </div>\n      {% } %}\n    </div>",
      footer: '',
    },
    rowClass: '',
    addAnother: '',
    modal: false,
    saveRow: '',
    removeRow: '',
    persistent: true,
    inlineEdit: false,
    protected: false,
    dbIndex: false,
    encrypted: false,
    redrawOn: '',
    clearOnHide: true,
    // eslint-disable-next-line max-len
    customDefaultValue: 'value = [{ textfieldLatest: "test", textfield3: "444", specializationEndDate: "dd", datetimeLatest: "ddd" }]',
    calculateValue: '',
    calculateServer: false,
    allowCalculateOverride: false,
    validateOn: 'change',
    validate: {
      required: false,
      customMessage: '',
      custom: '',
      customPrivate: false,
      json: '',
      strictDateValidation: false,
      multiple: false,
      unique: false,
      maxLength: 5,
    },
    rowDrafts: false,
    key: 'editGrid',
    tags: [],
    properties: {},
    conditional: {
      show: null,
      when: null,
      eq: '',
      json: '',
    },
    customConditional: '',
    logic: [],
    attributes: {},
    overlay: {
      style: '',
      page: '',
      left: '',
      top: '',
      width: '',
      height: '',
    },
    type: 'editgridLatest',
    input: true,
    placeholder: '',
    prefix: '',
    suffix: '',
    multiple: false,
    defaultValue: null,
    unique: false,
    refreshOn: '',
    dataGridLabel: false,
    errorLabel: '',
    widget: null,
    showCharCount: false,
    showWordCount: false,
    allowMultipleMasks: false,
    tree: true,
    defaultOpen: false,
    components: [
      {
        label: 'Attached documents',
        labelPosition: 'top',
        description: 'description',
        tooltip: '',
        customClass: '',
        tabindex: '',
        hidden: false,
        hideLabel: false,
        autofocus: false,
        disabled: false,
        tableView: false,
        modalEdit: false,
        storage: 'base64',
        dir: '',
        fileNameTemplate: '',
        image: false,
        uploadOnly: false,
        webcam: false,
        fileTypes: [
          {
            label: '',
            value: '',
          },
        ],
        filePattern: 'application/pdf,image/jpeg,image/png',
        fileMinSize: '0KB',
        fileMaxSize: '50MB',
        multiple: false,
        persistent: true,
        protected: false,
        dbIndex: false,
        encrypted: false,
        redrawOn: '',
        clearOnHide: true,
        customDefaultValue: '',
        calculateValue: '',
        calculateServer: false,
        allowCalculateOverride: false,
        validate: {
          required: false,
          customMessage: 'Please upload a file',
          custom: '',
          customPrivate: false,
          json: '',
          strictDateValidation: false,
          multiple: false,
          unique: false,
        },
        errorLabel: '',
        key: 'premisesFile',
        tags: [],
        properties: {},
        customConditional: '',
        logic: [],
        attributes: {},
        overlay: {
          style: '',
          page: '',
          left: '',
          top: '',
          width: '',
          height: '',
        },
        type: 'fileLatest',
        url: '/documents',
        imageSize: '200',
        input: true,
        placeholder: '',
        prefix: '',
        suffix: '',
        defaultValue: null,
        unique: false,
        refreshOn: '',
        widget: null,
        validateOn: 'change',
        showCharCount: false,
        showWordCount: false,
        allowMultipleMasks: false,
        privateDownload: false,
        id: 'euri0zr',
        options: '',
        fileKey: '',
        conditional: {
          show: true,
          when: 'editGrid.textfield2',
          eq: 'false',
          json: '',
        },
      },
      {
        label: 'Text Field',
        labelPosition: 'top',
        placeholder: '',
        description: 'description',
        tooltip: '',
        prefix: '',
        suffix: '',
        widget: {
          type: 'input',
        },
        inputMask: '',
        allowMultipleMasks: false,
        customClass: '',
        tabindex: '',
        autocomplete: '',
        hidden: false,
        hideLabel: false,
        showWordCount: false,
        showCharCount: false,
        mask: false,
        autofocus: false,
        spellcheck: true,
        disabled: false,
        tableView: false,
        modalEdit: false,
        multiple: false,
        persistent: true,
        inputFormat: 'plain',
        protected: false,
        dbIndex: false,
        case: '',
        encrypted: false,
        redrawOn: '',
        clearOnHide: true,
        customDefaultValue: '',
        calculateValue: '',
        calculateServer: false,
        allowCalculateOverride: false,
        validateOn: 'change',
        validate: {
          required: false,
          pattern: '',
          customMessage: '',
          custom: '',
          customPrivate: false,
          json: '',
          minLength: '',
          maxLength: '',
          strictDateValidation: false,
          multiple: false,
          unique: false,
        },
        unique: false,
        errorLabel: '',
        key: 'textfieldLatest',
        tags: [],
        properties: {},
        conditional: {
          show: null,
          when: null,
          eq: '',
          json: '',
        },
        customConditional: '',
        logic: [],
        attributes: {},
        overlay: {
          style: '',
          page: '',
          left: '',
          top: '',
          width: '',
          height: '',
        },
        type: 'textfieldLatest',
        input: true,
        refreshOn: '',
        dataGridLabel: false,
        inputType: 'text',
        id: 'ekt1lgb',
        defaultValue: null,
      },
      {
        label: 'Text Field 2',
        labelPosition: 'top',
        placeholder: '',
        description: 'description',
        tooltip: '',
        prefix: '',
        suffix: '',
        widget: {
          type: 'input',
        },
        inputMask: '',
        allowMultipleMasks: false,
        customClass: '',
        tabindex: '',
        autocomplete: '',
        hidden: false,
        hideLabel: false,
        showWordCount: false,
        showCharCount: false,
        mask: false,
        autofocus: false,
        spellcheck: true,
        disabled: false,
        tableView: true,
        modalEdit: false,
        multiple: false,
        persistent: true,
        inputFormat: 'plain',
        protected: false,
        dbIndex: false,
        case: '',
        encrypted: false,
        redrawOn: '',
        clearOnHide: true,
        customDefaultValue: '',
        calculateValue: '',
        calculateServer: false,
        allowCalculateOverride: false,
        validateOn: 'change',
        validate: {
          required: false,
          pattern: '',
          customMessage: '',
          custom: '',
          customPrivate: false,
          json: '',
          minLength: '',
          maxLength: '',
          strictDateValidation: false,
          multiple: false,
          unique: false,
        },
        unique: false,
        errorLabel: '',
        key: 'textfield2',
        tags: [],
        properties: {},
        conditional: {
          show: null,
          when: null,
          eq: '',
          json: '',
        },
        customConditional: '',
        logic: [],
        attributes: {},
        overlay: {
          style: '',
          page: '',
          left: '',
          top: '',
          width: '',
          height: '',
        },
        type: 'checkbox',
        input: true,
        refreshOn: '',
        dataGridLabel: false,
        id: 'ekt1lgb2',
        defaultValue: null,
      },
      {
        label: 'Text Field3',
        labelPosition: 'top',
        placeholder: '',
        description: 'description',
        tooltip: '',
        prefix: '',
        suffix: '',
        inputMask: '',
        allowMultipleMasks: false,
        customClass: '',
        tabindex: '',
        autocomplete: '',
        hidden: false,
        hideLabel: false,
        showWordCount: false,
        showCharCount: false,
        mask: false,
        autofocus: false,
        spellcheck: true,
        disabled: false,
        tableView: true,
        modalEdit: false,
        multiple: false,
        persistent: true,
        inputFormat: 'plain',
        protected: false,
        dbIndex: false,
        case: '',
        encrypted: false,
        redrawOn: '',
        clearOnHide: true,
        customDefaultValue: '',
        calculateValue: '',
        calculateServer: false,
        allowCalculateOverride: false,
        validateOn: 'change',
        validate: {
          required: false,
          pattern: '',
          customMessage: '',
          custom: '',
          customPrivate: false,
          json: '',
          minLength: '',
          maxLength: '',
          strictDateValidation: false,
          multiple: false,
          unique: false,
        },
        unique: false,
        errorLabel: '',
        key: 'textfield3',
        tags: [],
        properties: {},
        conditional: {
          show: null,
          when: null,
          eq: '',
          json: '',
        },
        customConditional: '',
        logic: [],
        attributes: {},
        overlay: {
          style: '',
          page: '',
          left: '',
          top: '',
          width: '',
          height: '',
        },
        type: 'numberLatest',
        input: true,
        refreshOn: '',
        dataGridLabel: false,
        inputType: 'text',
        id: 'ekt1lgb3',
        defaultValue: null,
      },
      {
        label: 'Text Field 4',
        labelPosition: 'top',
        placeholder: '',
        description: 'description',
        tooltip: '',
        prefix: '',
        suffix: '',
        widget: {
          type: 'input',
        },
        inputMask: '',
        allowMultipleMasks: false,
        customClass: '',
        tabindex: '',
        autocomplete: '',
        hidden: false,
        hideLabel: false,
        showWordCount: false,
        showCharCount: false,
        mask: false,
        autofocus: false,
        spellcheck: true,
        disabled: false,
        tableView: true,
        modalEdit: false,
        multiple: false,
        persistent: true,
        inputFormat: 'plain',
        protected: false,
        dbIndex: false,
        case: '',
        encrypted: false,
        redrawOn: '',
        clearOnHide: true,
        customDefaultValue: '',
        calculateValue: '',
        calculateServer: false,
        allowCalculateOverride: false,
        validateOn: 'change',
        validate: {
          required: false,
          pattern: '',
          customMessage: '',
          custom: '',
          customPrivate: false,
          json: '',
          minLength: '',
          maxLength: '',
          strictDateValidation: false,
          multiple: false,
          unique: false,
        },
        unique: false,
        errorLabel: '',
        key: 'textfield4',
        tags: [],
        properties: {},
        conditional: {
          show: null,
          when: null,
          eq: '',
          json: '',
        },
        customConditional: '',
        logic: [],
        attributes: {},
        overlay: {
          style: '',
          page: '',
          left: '',
          top: '',
          width: '',
          height: '',
        },
        type: 'textfield',
        input: true,
        refreshOn: '',
        dataGridLabel: false,
        inputType: 'text',
        id: 'ekt1lgb4',
        defaultValue: null,
      },
      {
        label: 'Date / Time',
        labelPosition: 'top',
        displayInTimezone: 'viewer',
        useLocaleSettings: false,
        allowInput: true,
        format: 'yyyy-MM-dd hh:mm a',
        placeholder: '',
        description: '',
        tooltip: '',
        customClass: '',
        tabindex: '',
        hidden: false,
        hideLabel: false,
        autofocus: false,
        disabled: false,
        tableView: false,
        modalEdit: false,
        enableDate: true,
        enableMinDateInput: false,
        datePicker: {
          minDate: null,
          maxDate: null,
          disable: '',
          disableFunction: '',
          disableWeekends: false,
          disableWeekdays: false,
          showWeeks: true,
          startingDay: 0,
          initDate: '',
          minMode: 'day',
          maxMode: 'year',
          yearRows: 4,
          yearColumns: 5,
        },
        enableMaxDateInput: false,
        enableTime: true,
        timePicker: {
          showMeridian: true,
          hourStep: 1,
          minuteStep: 1,
          readonlyInput: false,
          mousewheel: true,
          arrowkeys: true,
        },
        multiple: false,
        defaultValue: '',
        defaultDate: '',
        customOptions: {},
        persistent: true,
        protected: false,
        dbIndex: false,
        encrypted: false,
        redrawOn: '',
        clearOnHide: true,
        customDefaultValue: '',
        calculateValue: '',
        calculateServer: false,
        allowCalculateOverride: false,
        validate: {
          required: false,
          customMessage: '',
          custom: '',
          customPrivate: false,
          json: '',
          strictDateValidation: false,
          multiple: false,
          unique: false,
        },
        unique: false,
        validateOn: 'change',
        errorLabel: '',
        key: 'dateTime',
        tags: [],
        properties: {},
        conditional: {
          show: null,
          when: null,
          eq: '',
          json: '',
        },
        customConditional: '',
        logic: [],
        attributes: {},
        overlay: {
          style: '',
          page: '',
          left: '',
          top: '',
          width: '',
          height: '',
        },
        type: 'datetime',
        timezone: '',
        input: true,
        prefix: '',
        suffix: '',
        refreshOn: '',
        widget: {
          type: 'calendar',
          displayInTimezone: 'viewer',
          locale: 'ua',
          useLocaleSettings: true,
          allowInput: true,
          mode: 'single',
          enableTime: true,
          noCalendar: false,
          format: 'yyyy-MM-dd hh:mm a',
          hourIncrement: 1,
          minuteIncrement: 1,
          time_24hr: false,
          minDate: null,
          disabledDates: '',
          disableWeekends: false,
          disableWeekdays: false,
          disableFunction: '',
          maxDate: null,
        },
        showCharCount: false,
        showWordCount: false,
        allowMultipleMasks: false,
        datepickerMode: 'day',
        id: 'ehfnmy',
      },
      {
        label: 'Date / Time',
        labelPosition: 'top',
        allowInput: true,
        format: 'yyyy-MM-dd hh:mm a',
        placeholder: '',
        description: '',
        tooltip: '',
        tabindex: '',
        hidden: false,
        hideLabel: false,
        disabled: false,
        tableView: true,
        modalEdit: false,
        enableDate: true,
        datePicker: {
          minDate: null,
          maxDate: null,
          disableWeekends: false,
          disableWeekdays: false,
          disableFunction: '',
          showWeeks: true,
          startingDay: 0,
          initDate: '',
          minMode: 'day',
          maxMode: 'year',
          yearRows: 4,
          yearColumns: 5,
        },
        enableTime: true,
        defaultValue: '',
        redrawOn: '',
        clearOnHide: true,
        customDefaultValue: '',
        calculateValue: '',
        allowCalculateOverride: false,
        validateOn: 'change',
        validate: {
          required: false,
          customMessage: '',
          custom: '',
          customPrivate: false,
          strictDateValidation: false,
          multiple: false,
          unique: false,
        },
        key: 'datetimeLatest',
        conditional: {
          show: null,
          when: null,
          eq: '',
          json: '',
        },
        customConditional: '',
        type: 'datetimeLatest',
        timezone: '',
        input: true,
        prefix: '',
        customClass: '',
        suffix: '',
        multiple: false,
        protected: false,
        unique: false,
        persistent: true,
        refreshOn: '',
        dataGridLabel: false,
        errorLabel: '',
        autofocus: false,
        dbIndex: false,
        calculateServer: false,
        widget: null,
        attributes: {},
        overlay: {
          style: '',
          left: '',
          top: '',
          width: '',
          height: '',
        },
        encrypted: false,
        showCharCount: false,
        showWordCount: false,
        properties: {},
        allowMultipleMasks: false,
        useLocaleSettings: false,
        defaultDate: '',
        displayInTimezone: 'viewer',
        datepickerMode: 'day',
        timePicker: {
          hourStep: 1,
          minuteStep: 1,
          showMeridian: true,
          readonlyInput: false,
          mousewheel: true,
          arrowkeys: true,
        },
        customOptions: {},
        id: 'e9xb3y',
      },
      {
        label: 'Дата закінчення спеціалізації',
        labelPosition: 'top',
        displayInTimezone: 'viewer',
        useLocaleSettings: false,
        allowInput: true,
        format: 'yyyy-MM-dd',
        placeholder: '',
        description: '',
        tooltip: '',
        customClass: '',
        tabindex: '',
        hidden: false,
        hideLabel: false,
        autofocus: false,
        disabled: false,
        tableView: true,
        modalEdit: false,
        enableDate: true,
        enableMinDateInput: false,
        datePicker: {
          minDate: '1900-01-01T00:00:00+02:02',
          maxDate: '2100-01-01T00:00:00+02:00',
          disable: '',
          disableFunction: '',
          disableWeekends: false,
          disableWeekdays: false,
          showWeeks: true,
          startingDay: 0,
          initDate: '',
          minMode: 'day',
          maxMode: 'year',
          yearRows: 4,
          yearColumns: 5,
        },
        enableMaxDateInput: false,
        enableTime: false,
        timePicker: {
          showMeridian: false,
          hourStep: 1,
          minuteStep: 1,
          readonlyInput: false,
          mousewheel: true,
          arrowkeys: true,
        },
        multiple: false,
        defaultValue: '',
        defaultDate: '',
        customOptions: {},
        persistent: true,
        protected: false,
        dbIndex: false,
        encrypted: false,
        redrawOn: '',
        clearOnHide: true,
        customDefaultValue: '',
        calculateValue: '',
        calculateServer: false,
        allowCalculateOverride: false,
        validate: {
          required: false,
          customMessage: '',
          custom: '',
          customPrivate: false,
          json: '',
          strictDateValidation: false,
          multiple: false,
          unique: false,
        },
        unique: false,
        validateOn: 'change',
        errorLabel: '',
        key: 'specializationEndDate',
        tags: [],
        properties: {},
        conditional: {
          show: true,
          when: 'editGrid.textfield2',
          eq: 'false',
          json: '',
        },
        customConditional: '',
        logic: [],
        attributes: {},
        overlay: {
          style: '',
          page: '',
          left: '',
          top: '',
          width: '',
          height: '',
        },
        type: 'datetime',
        timezone: '',
        input: true,
        widget: {
          type: 'calendar',
          displayInTimezone: 'viewer',
          locale: {
            firstDayOfWeek: 1,
            weekdays: {
              shorthand: [
                'Нд',
                'Пн',
                'Вт',
                'Ср',
                'Чт',
                'Пт',
                'Сб',
              ],
              longhand: [
                'Неділя',
                'Понеділок',
                'Вівторок',
                'Середа',
                'Четвер',
                'П\'ятниця',
                'Субота',
              ],
            },
            months: {
              shorthand: [
                'Січ',
                'Лют',
                'Бер',
                'Кві',
                'Тра',
                'Чер',
                'Лип',
                'Сер',
                'Вер',
                'Жов',
                'Лис',
                'Гру',
              ],
              longhand: [
                'Січень',
                'Лютий',
                'Березень',
                'Квітень',
                'Травень',
                'Червень',
                'Липень',
                'Серпень',
                'Вересень',
                'Жовтень',
                'Листопад',
                'Грудень',
              ],
            },
            time_24hr: true,
          },
          useLocaleSettings: false,
          allowInput: true,
          mode: 'single',
          enableTime: false,
          noCalendar: false,
          format: 'yyyy-MM-dd',
          hourIncrement: 1,
          minuteIncrement: 1,
          time_24hr: true,
          minDate: '1900-01-01T00:00:00+02:02',
          disabledDates: '',
          disableWeekends: false,
          disableWeekdays: false,
          disableFunction: '',
          maxDate: '2100-01-01T00:00:00+02:00',
        },
        prefix: '',
        suffix: '',
        refreshOn: '',
        showCharCount: false,
        showWordCount: false,
        allowMultipleMasks: false,
        datepickerMode: 'day',
        id: 'emd5ub8',
      },
      {
        label: 'Text Field 5',
        labelPosition: 'top',
        placeholder: '',
        description: 'description',
        tooltip: '',
        prefix: '',
        suffix: '',
        widget: {
          type: 'input',
        },
        inputMask: '',
        allowMultipleMasks: false,
        customClass: '',
        tabindex: '',
        autocomplete: '',
        hidden: false,
        hideLabel: false,
        showWordCount: false,
        showCharCount: false,
        mask: false,
        autofocus: false,
        spellcheck: true,
        disabled: false,
        tableView: true,
        modalEdit: false,
        multiple: false,
        persistent: true,
        inputFormat: 'plain',
        protected: false,
        dbIndex: false,
        case: '',
        encrypted: false,
        redrawOn: '',
        clearOnHide: true,
        customDefaultValue: '',
        calculateValue: '',
        calculateServer: false,
        allowCalculateOverride: false,
        validateOn: 'change',
        validate: {
          required: false,
          pattern: '',
          customMessage: '',
          custom: '',
          customPrivate: false,
          json: '',
          minLength: '',
          maxLength: '',
          strictDateValidation: false,
          multiple: false,
          unique: false,
        },
        unique: false,
        errorLabel: '',
        key: 'textfield5',
        tags: [],
        properties: {},
        conditional: {
          show: null,
          when: null,
          eq: '',
          json: '',
        },
        customConditional: '',
        logic: [],
        attributes: {},
        overlay: {
          style: '',
          page: '',
          left: '',
          top: '',
          width: '',
          height: '',
        },
        type: 'textfield',
        input: true,
        refreshOn: '',
        dataGridLabel: false,
        inputType: 'text',
        id: 'ekt1lgb5',
        defaultValue: null,
      },
    ],
    id: 'elp91b',
  },
  {
    type: 'button',
    label: 'Submit',
    key: 'submit',
    size: 'md',
    block: false,
    action: 'submit',
    theme: 'primary',
    input: true,
    placeholder: '',
    prefix: '',
    customClass: '',
    suffix: '',
    multiple: false,
    defaultValue: null,
    protected: false,
    unique: false,
    persistent: false,
    hidden: false,
    clearOnHide: true,
    refreshOn: '',
    redrawOn: '',
    tableView: false,
    modalEdit: false,
    dataGridLabel: true,
    labelPosition: 'top',
    errorLabel: '',
    tooltip: '',
    hideLabel: false,
    tabindex: '',
    disabled: false,
    autofocus: false,
    dbIndex: false,
    customDefaultValue: '',
    calculateValue: '',
    calculateServer: false,
    widget: {
      type: 'input',
    },
    attributes: {},
    validateOn: 'change',
    validate: {
      required: false,
      custom: '',
      customPrivate: false,
      strictDateValidation: false,
      multiple: false,
      unique: false,
    },
    conditional: {
      show: null,
      when: null,
      eq: '',
    },
    overlay: {
      style: '',
      left: '',
      top: '',
      width: '',
      height: '',
    },
    allowCalculateOverride: false,
    encrypted: false,
    showCharCount: false,
    showWordCount: false,
    properties: {},
    allowMultipleMasks: false,
    leftIcon: '',
    rightIcon: '',
    id: 'ey7dq4',
  },
];

