/// <reference types="react-scripts" />
declare module 'react-formio';
declare module 'react-input-mask';
declare module 'formiojs/components/checkbox/Checkbox.form';
declare module 'formiojs/components/editgrid/EditGrid.form';
declare module 'formiojs/components/datetime/DateTime.form';
declare module 'formiojs/utils/builder';
declare module 'formiojs/components/radio/Radio.form';
declare module 'formiojs/WebformBuilder';
declare module 'formiojs/components/selectboxes/SelectBoxes.form';
declare module 'formiojs/components/textfield/TextField.form';
declare module 'formiojs/components/number/Number.form';
declare module 'formiojs/components/email/Email.form';
declare module 'formiojs/components/select/Select.form';
declare module 'formiojs/components/content/Content.form';
declare module 'formiojs/components/textarea/TextArea.form';
declare module 'formiojs/components/file/File.form';
declare module 'formiojs/components/button/Button.form';
declare module 'formiojs/components/fieldset/Fieldset.form';
declare module 'formiojs/components/columns/Columns.form'
declare module 'formiojs/components/table/Table.form';
declare module 'formiojs/utils/utils';
declare module '*.woff2';
declare module '*.svg';
declare module '*.png';
